# Generated by Django 4.1.2 on 2023-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letslearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='email_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mobileno',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
